version: '3'

services:
  nginx:
    image: nginx
    container_name: "jgw-nginx"
    ports:
      - "80:80"
    volumes:
      - ./../src:/src
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./php
    container_name: "jgw-php"
    volumes:
      - ./../src:/src
      - ./php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    container_name: "jgw-mysql"
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    container_name: "jgw-redis"
    ports:
      - 6379:6379