version: '3'

services:
  nginx:
    image: nginx
    container_name: "nginx"
    ports:
      - "80:80"
    volumes:
      - ./../src:/src
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./php
    container_name: "php"
    volumes:
      - ./../src:/src

  mysql:
    image: mysql
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - 6379:6379