version: '3'

services:
  nginx:
    image: nginx:1-alpine
    container_name: "jgw-nginx"
    ports:
      - "80:80"
    volumes:
      - ./../src:/src
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./php
    container_name: "jgw-php"
    volumes:
      - ./../src:/src
      - ./php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:8
    container_name: "jgw-mysql"
    ports:
      - 3306:3306
    restart: always
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql/mount/var/lib/mysql:/var/lib/mysql
      - ./mysql/mount/etc/my.cnf:/etc/my.cnf

  redis:
    image: redis:5-alpine
    container_name: "jgw-redis"
    ports:
      - 6379:6379